export const leader_statistics = {
  total_stats: {
    points: {
      "Erling Haaland": 561.5,
      "Harry Kane": 540.0,
      "Bruno Fernandes": 508.0,
      "Mohamed Salah": 505.0,
      "Bukayo Saka": 499.0,
      "Martin Odegaard": 472.0,
      "Kevin De Bruyne": 461.5,
      "Gabriel Martinelli": 435.5,
      "Solly March": 416.5,
      "Marcus Rashford": 416.5,
    },
    cleansheet: {
      "David De Gea": 17,
      Alisson: 14,
      "Nick Pope": 14,
      "Aaron Ramsdale": 13,
      Ederson: 11,
      "Emiliano Martinez": 11,
      "Jose Sa": 11,
      "David Raya": 11,
      "Kepa Arrizabalaga": 9,
      "Lukasz Fabianski": 9,
    },
    tackles_total: {
      "Joao Palhinha": 143,
      "Moises Caicedo": 100,
      "Idrissa Gueye": 90,
      Casemiro: 89,
      "Tyler Adams": 89,
      "Timothy Castagne": 84,
      "Pascal Struijk": 82,
      "Kenny Tete": 81,
      "Declan Rice": 80,
      "Ruben Neves": 78,
    },
    blocked_shots: {
      "James Tarkowski": 78,
      "Max Kilman": 42,
      "Ben Mee": 41,
      "Wout Faes": 37,
      "Craig Dawson": 29,
      "Thiago Silva": 28,
      "Lisandro Martinez": 27,
      "Jan Bednarek": 27,
      "Chris Mepham": 27,
      "Lewis Dunk": 27,
    },
    interceptions: {
      "Declan Rice": 62,
      "Cheick Doucoure": 57,
      "Moises Caicedo": 54,
      "Idrissa Gueye": 53,
      "Tomas Soucek": 53,
      "Antonee Robinson": 53,
      "James Ward-Prowse": 52,
      "Tyrone Mings": 51,
      "Kenny Tete": 50,
      "Fabian Schar": 50,
    },
    total_goals: {
      "Erling Haaland": 36,
      "Harry Kane": 28,
      "Ivan Toney": 20,
      "Mohamed Salah": 19,
      "Callum Wilson": 18,
      "Marcus Rashford": 17,
      "Martin Odegaard": 15,
      "Gabriel Martinelli": 15,
      "Aleksandar Mitrovic": 14,
      "Ollie Watkins": 14,
    },
    goals_conceded: {
      "Illan Meslier": 74,
      "Mark Travers": 69,
      "Gavin Bazunu": 69,
      "Daniel Iversen": 67,
      "Wayne Hennessey": 64,
      "Danny Ward": 64,
      "Fraser Forster": 61,
      "Asmir Begovic": 57,
      "Jordan Pickford": 57,
      "Joel Robles": 56,
    },
    assists: {
      "Kevin De Bruyne": 16,
      "Bukayo Saka": 11,
      "Mohamed Salah": 11,
      "Riyad Mahrez": 10,
      "Leandro Trossard": 10,
      "Michael Olise": 10,
      "James Maddison": 9,
      "Christian Eriksen": 8,
      "Bruno Fernandes": 8,
      "Ivan Perisic": 8,
    },
    minutes: {
      Alisson: 3351,
      "David De Gea": 3347,
      "James Tarkowski": 3340,
      "Aaron Ramsdale": 3336,
      "David Raya": 3335,
      "Harry Kane": 3322,
      "Gabriel Magalhaes": 3321,
      "Alex Iwobi": 3301,
      "James Ward-Prowse": 3290,
      "Lewis Dunk": 3276,
    },
    rating: {
      "Kieran Trippier": 284.0,
      "Harry Kane": 274.2,
      "Bruno Fernandes": 273.4,
      "Bukayo Saka": 270.7,
      "James Ward-Prowse": 268.5,
      "James Tarkowski": 267.3,
      "David Raya": 266.2,
      "Martin Odegaard": 264.8,
      "Mohamed Salah": 264.5,
      "Trent Alexander-Arnold": 263.7,
    },
    saves: {
      "David Raya": 152,
      "Bernd Leno": 138,
      "Jordan Pickford": 123,
      Alisson: 108,
      "Lukasz Fabianski": 106,
      "Jose Sa": 105,
      Neto: 100,
      "David De Gea": 99,
      "Emiliano Martinez": 95,
      "Aaron Ramsdale": 94,
    },
    key_passes: {
      "Bruno Fernandes": 114,
      "Kieran Trippier": 111,
      "Kevin De Bruyne": 99,
      "Pascal Gross": 81,
      "James Ward-Prowse": 76,
      "Bukayo Saka": 75,
      "Martin Odegaard": 74,
      "James Maddison": 68,
      "Trent Alexander-Arnold": 68,
      "Solly March": 67,
    },
    total_passes: {
      "Lewis Dunk": 3178,
      Rodri: 2974,
      "Virgil van Dijk": 2573,
      "Gabriel Magalhaes": 2338,
      "Pierre-Emile Hojbjerg": 2254,
      "Trent Alexander-Arnold": 2233,
      "Moises Caicedo": 2164,
      "Marc Guehi": 2092,
      "Ruben Dias": 2067,
      "Max Kilman": 2041,
    },
    pass_accuracy: {
      "Lewis Dunk": 2874.0,
      Rodri: 2716.0,
      "Virgil van Dijk": 2329.0,
      "Gabriel Magalhaes": 2095.0,
      "Pierre-Emile Hojbjerg": 1998.0,
      "Moises Caicedo": 1923.0,
      "Ruben Dias": 1916.0,
      "Manuel Akanji": 1885.0,
      "Marc Guehi": 1787.0,
      "Thiago Silva": 1786.0,
    },
    total_shots: {
      "Erling Haaland": 107,
      "Harry Kane": 97,
      "Mohamed Salah": 91,
      "Ivan Toney": 78,
      "Marcus Rashford": 77,
      "Aleksandar Mitrovic": 73,
      "Darwin Nunez": 71,
      "Bruno Fernandes": 68,
      "Ollie Watkins": 68,
      "Alexis Mac Allister": 64,
    },
    on_target_shots: {
      "Erling Haaland": 60,
      "Harry Kane": 60,
      "Marcus Rashford": 48,
      "Mohamed Salah": 46,
      "Ollie Watkins": 45,
      "Ivan Toney": 42,
      "Heung-min Son": 40,
      "Darwin Nunez": 37,
      "Callum Wilson": 35,
      "Aleksandar Mitrovic": 34,
    },
    dribble_attempts: {
      "Bukayo Saka": 126,
      "Marcus Rashford": 126,
      "Jordan Ayew": 119,
      "Wilfried Zaha": 116,
      "Mohamed Salah": 114,
      "Gabriel Martinelli": 113,
      "Kaoru Mitoma": 109,
      "Michael Olise": 108,
      "Dwight McNeil": 103,
      "Alex Iwobi": 103,
    },
    successful_dribbles: {
      "Eberechi Eze": 65,
      "Jordan Ayew": 61,
      "Gabriel Martinelli": 58,
      "Solly March": 57,
      "Bukayo Saka": 57,
      "Kaoru Mitoma": 54,
      "Dwight McNeil": 53,
      "Alex Iwobi": 53,
      "Marcus Rashford": 53,
      Joelinton: 52,
    },
    dribbled_past: {
      "Joao Palhinha": 59,
      "Mathias Jensen": 58,
      "Emiliano Buendia": 48,
      "Marc Roca": 45,
      "Kieran Trippier": 44,
      "Luke Ayling": 42,
      Casemiro: 41,
      "Pierre-Emile Hojbjerg": 41,
      Jorginho: 40,
      "Bruno Fernandes": 39,
    },
    duels_total: {
      "Jordan Ayew": 567,
      "Ivan Toney": 478,
      Joelinton: 474,
      "Joao Palhinha": 455,
      "Dominic Solanke": 431,
      "Morgan Gibbs-White": 417,
      "Bukayo Saka": 415,
      "Jarrod Bowen": 412,
      "Gabriel Jesus": 409,
      "Tomas Soucek": 403,
    },
    duels_won: {
      "Joao Palhinha": 272,
      "Jordan Ayew": 262,
      Joelinton: 221,
      "Ivan Toney": 218,
      "Bruno Guimaraes": 217,
      "Moises Caicedo": 214,
      "Tomas Soucek": 207,
      "Ben Mee": 198,
      "Bukayo Saka": 197,
      "John McGinn": 190,
    },
    yellow: {
      "Joao Palhinha": 13,
      Joelinton: 12,
      "Ruben Neves": 12,
      "Conor Gallagher": 11,
      "Cristian Romero": 11,
      "Cheick Doucoure": 11,
      Fabinho: 11,
      "Nelson Semedo": 11,
      "James Maddison": 10,
      "Adam Smith": 10,
    },
    red: {
      Casemiro: 2,
      "Wout Faes": 1,
      "Junior Firpo": 1,
      "Diego Costa": 1,
      "Mario Lemina": 1,
      "Joao Felix": 1,
      "James Tomkins": 1,
      "Matheus Nunes": 1,
      "Lucas Moura": 1,
      "Kiernan Dewsbury-Hall": 1,
    },
    fouls_drawn: {
      "Jordan Ayew": 88,
      "Bruno Guimaraes": 79,
      "Jack Grealish": 78,
      "James Maddison": 77,
      "Wilfried Zaha": 77,
      "Ivan Toney": 74,
      "Jarrod Bowen": 68,
      "Michael Olise": 67,
      "John McGinn": 64,
      "Ezri Konsa": 64,
    },
    fouls_committed: {
      Joelinton: 65,
      "Moises Caicedo": 64,
      "Kai Havertz": 60,
      "Ivan Toney": 52,
      "Jeffrey Schlupp": 51,
      Fabinho: 51,
      "Tomas Soucek": 50,
      "Lucas Paqueta": 49,
      "Jordan Ayew": 48,
      "Ryan Yates": 48,
    },
    penalties_won: {
      "Jarrod Bowen": 3,
      "Ivan Toney": 3,
      Richarlison: 2,
      "Ilkay Gundogan": 2,
      "Kevin De Bruyne": 2,
      "John McGinn": 2,
      "Gabriel Jesus": 2,
      "Aleksandar Mitrovic": 2,
      "Jamie Vardy": 2,
      "Harry Wilson": 2,
    },
    penalties_commited: {
      "Lewis Dunk": 4,
      "Issa Diop": 2,
      "Jefferson Lerma": 2,
      "Gabriel Magalhaes": 2,
      "William Saliba": 2,
      "Pascal Struijk": 2,
      "Timothy Castagne": 2,
      "Wilfred Ndidi": 2,
      "Michael Keane": 2,
      "Joao Cancelo": 2,
    },
    penalties_scored: {
      "Erling Haaland": 7,
      "Alexis Mac Allister": 6,
      "Ivan Toney": 6,
      "Harry Kane": 5,
      "Said Benrahma": 4,
      "Aleksandar Mitrovic": 4,
      "Callum Wilson": 3,
      "Ruben Neves": 3,
      "Alexander Isak": 2,
      "Bruno Fernandes": 2,
    },
    penalties_missed: {
      "Aleksandar Mitrovic": 3,
      "Brennan Johnson": 2,
      "Wilfried Zaha": 2,
      "Mohamed Salah": 2,
      "Patrick Bamford": 2,
      "James Ward-Prowse": 2,
      "Jarrod Bowen": 1,
      "Bukayo Saka": 1,
      "Ollie Watkins": 1,
      "Andre Ayew": 1,
    },
    penalties_saved: {
      "Jose Sa": 2,
      "Nick Pope": 2,
      "Dean Henderson": 2,
      "Bernd Leno": 1,
      Alisson: 1,
      "Emiliano Martinez": 1,
      "Danny Ward": 1,
      "Gavin Bazunu": 1,
      "Jordan Pickford": 1,
      "Lukasz Fabianski": 1,
    },
  },
  avg_stats: {
    points: {
      "Erling Haaland": 16.0,
      "Harry Kane": 14.6,
      "Bruno Fernandes": 14.1,
      "James Maddison": 13.9,
      "Mohamed Salah": 13.6,
      "Bukayo Saka": 13.5,
      "Kevin De Bruyne": 13.2,
      "Martin Odegaard": 13.1,
      "Solly March": 12.6,
      "Gabriel Jesus": 12.5,
    },
    cleansheet: {
      "David De Gea": 0.5,
      "Nick Pope": 0.4,
      "Aaron Ramsdale": 0.4,
      Alisson: 0.4,
      "Hugo Lloris": 0.3,
      "Dean Henderson": 0.3,
      "David Raya": 0.3,
      "Jose Sa": 0.3,
      "Emiliano Martinez": 0.3,
      Ederson: 0.3,
    },
    tackles_total: {
      "Joao Palhinha": 4.2,
      "Tyler Adams": 3.7,
      Casemiro: 3.3,
      "Victor Kristiansen": 2.8,
      "Moises Caicedo": 2.8,
      "Idrissa Gueye": 2.8,
      "Serge Aurier": 2.7,
      "Kenny Tete": 2.6,
      "Enzo Fernandez": 2.6,
      Felipe: 2.5,
    },
    blocked_shots: {
      "James Tarkowski": 2.1,
      "Wout Faes": 1.2,
      "Craig Dawson": 1.1,
      "Ben Mee": 1.1,
      "Max Kilman": 1.1,
      "Nayef Aguerd": 1.1,
      "Mohammed Salisu": 1.0,
      "Thiago Silva": 1.0,
      "Lisandro Martinez": 1.0,
      "Ethan Pinnock": 0.9,
    },
    interceptions: {
      Felipe: 2.1,
      "Wesley Fofana": 1.7,
      "Cheick Doucoure": 1.7,
      "Armel Bella-Kotchap": 1.7,
      "Declan Rice": 1.7,
      "Idrissa Gueye": 1.7,
      "Cristian Romero": 1.6,
      "Kenny Tete": 1.6,
      "Antonee Robinson": 1.6,
      "Tyrone Mings": 1.5,
    },
    total_goals: {
      "Erling Haaland": 1.0,
      "Harry Kane": 0.8,
      "Ivan Toney": 0.6,
      "Aleksandar Mitrovic": 0.6,
      "Callum Wilson": 0.6,
      "Marcus Rashford": 0.5,
      "Mohamed Salah": 0.5,
      "Alexander Isak": 0.5,
      "Ollie Watkins": 0.4,
      "Harvey Barnes": 0.4,
    },
    goals_conceded: {
      "Joel Robles": 2.2,
      "Illan Meslier": 2.0,
      "Alex McCarthy": 2.0,
      "Keylor Navas": 1.9,
      "Gavin Bazunu": 1.9,
      "Mark Travers": 1.9,
      "Daniel Iversen": 1.8,
      "Wayne Hennessey": 1.8,
      Neto: 1.8,
      "Brandon Austin": 1.8,
    },
    assists: {
      "Kevin De Bruyne": 0.5,
      "Michael Olise": 0.3,
      "Riyad Mahrez": 0.3,
      "James Maddison": 0.3,
      "Mohamed Salah": 0.3,
      "Bukayo Saka": 0.3,
      "Christian Eriksen": 0.3,
      "Leandro Trossard": 0.3,
      "Dango Ouattara": 0.2,
      "Alex Moreno": 0.2,
    },
    minutes: {
      "Keylor Navas": 91.5,
      Alisson: 90.6,
      "David De Gea": 90.5,
      "Wout Faes": 90.3,
      "James Tarkowski": 90.3,
      "Jordan Pickford": 90.3,
      "Bruno Fernandes": 90.3,
      "Ethan Pinnock": 90.2,
      "Aaron Ramsdale": 90.2,
      "Marc Guehi": 90.1,
    },
    rating: {
      "Kieran Trippier": 7.7,
      "Bruno Fernandes": 7.6,
      "Martin Odegaard": 7.4,
      "Harry Kane": 7.4,
      "Erling Haaland": 7.4,
      "Ivan Toney": 7.3,
      "James Maddison": 7.3,
      "Ruben Neves": 7.3,
      "Bukayo Saka": 7.3,
      "Solly March": 7.3,
    },
    saves: {
      "David Raya": 4.1,
      "Bernd Leno": 3.7,
      "Jordan Pickford": 3.4,
      Neto: 3.3,
      "Dean Henderson": 3.1,
      "Keylor Navas": 3.0,
      "Hugo Lloris": 3.0,
      "Lukasz Fabianski": 3.0,
      Alisson: 2.9,
      "Jose Sa": 2.8,
    },
    key_passes: {
      "Bruno Fernandes": 3.2,
      "Kieran Trippier": 3.0,
      "Kevin De Bruyne": 2.8,
      "James Maddison": 2.3,
      "Pascal Gross": 2.2,
      "James Ward-Prowse": 2.1,
      "Martin Odegaard": 2.1,
      "Bukayo Saka": 2.0,
      "Solly March": 2.0,
      Willian: 1.8,
    },
    total_passes: {
      "Lewis Dunk": 85.9,
      Rodri: 82.6,
      "Virgil van Dijk": 78.0,
      "Enzo Fernandez": 77.9,
      "Thiago Silva": 69.9,
      "William Saliba": 69.0,
      "Manuel Akanji": 67.3,
      "Ruben Dias": 64.6,
      "Pierre-Emile Hojbjerg": 64.4,
      "Oleksandr Zinchenko": 63.4,
    },
    pass_accuracy: {
      "Lewis Dunk": 77.7,
      Rodri: 75.4,
      "Virgil van Dijk": 70.6,
      "Enzo Fernandez": 69.2,
      "Thiago Silva": 63.8,
      "William Saliba": 62.9,
      "Manuel Akanji": 62.8,
      "Ruben Dias": 59.9,
      "Pierre-Emile Hojbjerg": 57.1,
      "Gabriel Magalhaes": 56.6,
    },
    total_shots: {
      "Aleksandar Mitrovic": 3.2,
      "Erling Haaland": 3.1,
      "Harry Kane": 2.6,
      "Mohamed Salah": 2.5,
      "Ivan Toney": 2.4,
      "Darwin Nunez": 2.4,
      "Marcus Rashford": 2.3,
      "Gabriel Jesus": 2.2,
      "Callum Wilson": 2.0,
      Antony: 2.0,
    },
    on_target_shots: {
      "Erling Haaland": 1.7,
      "Harry Kane": 1.6,
      "Aleksandar Mitrovic": 1.5,
      "Marcus Rashford": 1.4,
      "Ivan Toney": 1.3,
      "Darwin Nunez": 1.3,
      "Mohamed Salah": 1.2,
      "Gabriel Jesus": 1.2,
      "Ollie Watkins": 1.2,
      "Alexander Isak": 1.1,
    },
    dribble_attempts: {
      "Wilfried Zaha": 4.3,
      "Marcus Tavernier": 3.9,
      "Marcus Rashford": 3.7,
      "Kamaldeen Sulemana": 3.6,
      "Dango Ouattara": 3.6,
      "Gabriel Jesus": 3.5,
      "Bukayo Saka": 3.4,
      "Dejan Kulusevski": 3.4,
      "Kaoru Mitoma": 3.2,
      "Noni Madueke": 3.2,
    },
    successful_dribbles: {
      "Allan Saint-Maximin": 2.0,
      "Marcus Tavernier": 1.9,
      "Wilfried Zaha": 1.9,
      "Kamaldeen Sulemana": 1.9,
      "Eberechi Eze": 1.8,
      "Noni Madueke": 1.8,
      "Gabriel Jesus": 1.7,
      "Dejan Kulusevski": 1.7,
      "Solly March": 1.7,
      "Dango Ouattara": 1.7,
    },
    dribbled_past: {
      "Enzo Fernandez": 1.9,
      "Joao Palhinha": 1.7,
      "Mathias Jensen": 1.6,
      Casemiro: 1.5,
      "Pedro Porro": 1.5,
      "Luke Ayling": 1.3,
      "Marc Roca": 1.3,
      "Emiliano Buendia": 1.3,
      "Lucas Paqueta": 1.3,
      Danilo: 1.2,
    },
    duels_total: {
      "Aleksandar Mitrovic": 16.5,
      "Gabriel Jesus": 16.4,
      "Jordan Ayew": 15.3,
      "Ivan Toney": 14.5,
      Joelinton: 14.4,
      "Wilfried Zaha": 13.9,
      "Dominic Solanke": 13.5,
      "Joao Palhinha": 13.4,
      "Dominic Calvert-Lewin": 12.8,
      "Lucas Paqueta": 12.2,
    },
    duels_won: {
      "Joao Palhinha": 8.0,
      "Aleksandar Mitrovic": 7.4,
      "Jordan Ayew": 7.1,
      Felipe: 7.0,
      "Bruno Guimaraes": 7.0,
      "Gabriel Jesus": 6.8,
      Joelinton: 6.7,
      "Ivan Toney": 6.6,
      Casemiro: 6.5,
      "Wilfried Zaha": 6.2,
    },
    yellow: {
      "Rodrigo Bentancur": 0.4,
      "Cristian Romero": 0.4,
      "Ruben Neves": 0.4,
      "Bobby Reid": 0.4,
      "Joao Palhinha": 0.4,
      Joelinton: 0.4,
      "Weston McKennie": 0.4,
      Fabinho: 0.3,
      "Kenny Tete": 0.3,
      "Boubakary Soumare": 0.3,
    },
    red: {
      "Joao Felix": 0.1,
      "Nathaniel Chalobah": 0.1,
      "Luis Sinisterra": 0.1,
      "Joao Cancelo": 0.1,
      Casemiro: 0.1,
      "Mario Lemina": 0.1,
      "Yasin Ayari": 0.0,
      "Cheick Doucoure": 0.0,
      "Tyrick Mitchell": 0.0,
      "Marc Guehi": 0.0,
    },
    fouls_drawn: {
      "Wilfried Zaha": 2.9,
      "James Maddison": 2.7,
      "Bruno Guimaraes": 2.5,
      "Jack Grealish": 2.4,
      "Jordan Ayew": 2.4,
      "Ivan Toney": 2.2,
      "Gabriel Jesus": 2.2,
      "Ryan Yates": 2.1,
      "James Justin": 2.1,
      "Michael Olise": 1.9,
    },
    fouls_committed: {
      Joelinton: 2.0,
      "Ryan Yates": 1.9,
      "Moises Caicedo": 1.8,
      "Lucas Paqueta": 1.8,
      "Kai Havertz": 1.7,
      "Gabriel Jesus": 1.7,
      Casemiro: 1.7,
      "Cristian Romero": 1.6,
      "Ivan Toney": 1.6,
      "Christian Norgaard": 1.6,
    },
    penalties_won: {
      "Bobby Decordova-Reid": 0.1,
      "Harry Kane": 0.1,
      "Reece James": 0.1,
      "Kevin De Bruyne": 0.1,
      "Anthony Martial": 0.1,
      "Lucas Paqueta": 0.1,
      "Samuel Edozie": 0.1,
      "Harry Wilson": 0.1,
      "Cody Gakpo": 0.1,
      "Kevin Schade": 0.1,
    },
    penalties_commited: {
      "Jonjo Shelvey": 0.1,
      "Ibrahima Konate": 0.1,
      "Kristoffer Ajer": 0.1,
      "Steve Cook": 0.1,
      "Marcos Senesi": 0.1,
      "Joao Cancelo": 0.1,
      "Lewis Dunk": 0.1,
      "Michael Keane": 0.1,
      "Moussa Niakhate": 0.1,
      "Wesley Fofana": 0.1,
    },
    penalties_scored: {
      "Ivan Toney": 0.2,
      "Aleksandar Mitrovic": 0.2,
      "Alexis Mac Allister": 0.2,
      "Erling Haaland": 0.2,
      "Bukayo Saka": 0.1,
      "Callum Wilson": 0.1,
      "Harry Kane": 0.1,
      "Anthony Martial": 0.1,
      "Alexander Isak": 0.1,
      "Dominic Calvert-Lewin": 0.1,
    },
    penalties_missed: {
      "James Ward-Prowse": 0.1,
      "Mohamed Salah": 0.1,
      "Wilfried Zaha": 0.1,
      "Aleksandar Mitrovic": 0.1,
      "Patrick Bamford": 0.1,
      "Brennan Johnson": 0.1,
      "Andre Ayew": 0.1,
      "Yasin Ayari": 0.0,
      "Jeffrey Schlupp": 0.0,
      "Cheick Doucoure": 0.0,
    },
    penalties_saved: {
      "Dean Henderson": 0.1,
      "Nick Pope": 0.1,
      "Jose Sa": 0.1,
      "Yasin Ayari": 0.0,
      "Jeffrey Schlupp": 0.0,
      "Cheick Doucoure": 0.0,
      "Tyrick Mitchell": 0.0,
      "Marc Guehi": 0.0,
      "Joachim Andersen": 0.0,
      "Nathaniel Clyne": 0.0,
    },
  },
};
